name       : starfighter
version    : 2.0.0.3
release    : 6
source     :
    - https://github.com/pr-starfighter/starfighter/archive/v2.0.0.3.tar.gz : 08440bc8555f1f8d88a5fcb777e42206a57ae2c7a6f6839cc9c2c458a3cd5dfb
homepage   : https://pr-starfighter.github.io/
license    :
    - CC-BY-3.0
    - CC-BY-SA-3.0
    - CC0-1.0
    - GPL-2.0-or-later
    - GPL-3.0-or-later 
component  : games.arcade
summary    : Project - Starfighter is a space shoot 'em up game
description: |
    Project: Starfighter is a space shoot 'em up game originally developed by Parallel Realities in 2002, and released in 2003. You assume the role of Chris Bainfield in his quest to put an end to WEAPCO, the weapons corporation which has enslaved the galaxy.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
setup      : |
    %patch -p1 < $pkgfiles/0001-make-install-fails-to-install-locale-en.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
    rm -f $installdir/usr/share/starfighter/locale/{build.py,genpot.sh,pr-starfighter.pot}
