name       : starfighter
version    : 2.2.1
release    : 10
source     :
    - https://github.com/pr-starfighter/starfighter/archive/v2.2.1.tar.gz : 53bb3122dbd6e50ec8dab831949fe427d1d22d905cbde658fd1842f1d7a7d406
homepage   : https://pr-starfighter.github.io/
license    :
    - CC-BY-3.0
    - CC-BY-SA-3.0
    - CC0-1.0
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : games.arcade
summary    : Project - Starfighter is a space shoot 'em up game
description: |
    Project: Starfighter is a space shoot 'em up game originally developed by Parallel Realities in 2002, and released in 2003. You assume the role of Chris Bainfield in his quest to put an end to WEAPCO, the weapons corporation which has enslaved the galaxy.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
    rm -f $installdir/usr/share/starfighter/locale/{build.py,genpot.sh,pr-starfighter.pot}
