name       : starfighter
version    : '2.4'
release    : 11
source     :
    - https://github.com/pr-starfighter/starfighter/archive/v2.4.tar.gz : d0757da7657253316053acf37dabf8e54607420d66a4d7cc2a9fc0d4b4d54074
homepage   : https://pr-starfighter.github.io/
license    :
    - CC-BY-3.0
    - CC-BY-SA-3.0
    - CC0-1.0
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : games.arcade
summary    : Project - Starfighter is a space shoot 'em up game
description: |
    Project: Starfighter is a space shoot 'em up game originally developed by Parallel Realities in 2002, and released in 2003. You assume the role of Chris Bainfield in his quest to put an end to WEAPCO, the weapons corporation which has enslaved the galaxy.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
    rm -f $installdir/usr/share/starfighter/locale/{build.py,genpot.sh,pr-starfighter.pot}
