name       : starfighter
version    : '1.6'
release    : 2
source     :
    - http://savannah.spinellicreations.com/starfighter/1.6/starfighter-1.6-src.tar.gz : f8c326956cc4e2c9b731abfaead2f0d111d7fc50e4d5af7f5111b4b1c0b465e1
license    :
    - CC-BY-3.0
    - CC-BY-SA-3.0
    - CC0-1.0
    - GPL-2.0
    - GPL-3.0
component  : games.arcade
summary    : Project - Starfighter is a space shoot 'em up game
description: |
    Project: Starfighter is a space shoot 'em up game originally developed by Parallel Realities in 2002, and released in 2003. You assume the role of Chris Bainfield in his quest to put an end to WEAPCO, the weapons corporation which has enslaved the galaxy.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
build      : |
    sed -i "s/games\/parallelrealities/starfighter/" Makefile
    sed -i "s/games\//bin\//" Makefile
    %make
install    : |
    %make_install
